version: '3.1'
services:
  springappcont:
    image: dockerwordnest/spring-boot-mongo:6
    ports:
    - 8080:8080
    networks:
    - springnetwork
  mongo:
    image: mongo
    volumes:
    - mongodb:/data/db
    networks:
    - springnetwork

volumes:
  mongodb:
     driver: local
networks:
  springnetwork:
    driver: bridge
